[package]
name = "tokenization"
version = "0.1.0"
edition = "2023_10"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html


[dependencies]
openzeppelin = "0.20.0"
starknet = "2.11.4"

[tool.voyager]
my_contract = { path = "AssetToken.cairo" }

[dev-dependencies]
snforge_std = "0.34.0"

[scripts]
test = "snforge test"

[[target.starknet-contract]]
casm = true
sierra = true

[tool.fmt]
sort-module-level-items = true

